services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: weather_data
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql_data:/var/lib/mysql

  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    container_name: grafana-container
    ports:
      - "3000:3000"

  app:
    build:
      dockerfile: Dockerfile
    container_name: garni_station_data-container
    restart: always
    network_mode: host
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - grafana
    volumes:
      - ./src:/app/src