{
 "title": "WeatherData",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Outdoor TEMP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT outdoorTempC FROM weather_data.weather_data_vt ORDER BY dateTime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Indoor TEMP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT indoorTempC FROM weather_data.weather_data_vt ORDER BY dateTime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Outdoor HUMIDITY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT outdoorHumidity FROM weather_data.weather_data_vt ORDER BY dateTime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Indoor HUMIDITY",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT indoorHumidity FROM weather_data.weather_data_vt ORDER BY dateTime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Outdoor TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT outdoorTempC, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Indoor TEMP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT indoorTempC, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Outdoor HUMIDITY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT outdoorHumidity, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Indoor HUMIDITY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT indoorHumidity, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT barometricPressure, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Wind Speed m/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT windSpeed, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Rain rate ACTUAL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT rainRate, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "Rain per Day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT SUM(rainRate) FROM weather_data.weather_data_vt WHERE dateTime >= NOW() - INTERVAL 24 HOUR;"
    }
   ]
  },
  {
   "title": "Rain per week",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT SUM(rainRate) FROM weather_data.weather_data_vt WHERE dateTime >= NOW() - INTERVAL 7 DAY;"
    }
   ]
  },
  {
   "title": "Rain LAST 30 days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT SUM(rainRate) FROM weather_data.weather_data_vt WHERE dateTime >= NOW() - INTERVAL 30 DAY;"
    }
   ]
  },
  {
   "title": "Rain grafana TIMERANGE",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT SUM(rainRate) FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime);"
    }
   ]
  },
  {
   "title": "Sun Radiation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT sunRadiation, dateTime FROM weather_data.weather_data_vt WHERE $__timeFilter(dateTime) ORDER BY dateTime DESC"
    }
   ]
  },
  {
   "title": "UV index",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT uvIndex FROM weather_data.weather_data_vt ORDER BY dateTime DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Wind Dirrection",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "weather_data",
     "rawSql": "SELECT windDirection FROM weather_data.weather_data_vt ORDER BY dateTime LIMIT 1"
    }
   ]
  }
 ]
}